### ISSUE TITLE
Service API returns 404

### ISSUE THREAD

**Issue by werenall** [tosdr/API#1]
Steps to reproduce:
`GET https://api.tosdr.org/service/v1/?service=wikipedia.org`

Expected output: valid response for Wikipedia
Actual output: server responses with 404

First observed: 2023/04/11 8:40PM CEST
![image](https://user-images.githubusercontent.com/18025307/231447614-7cf31c4f-0f85-44ca-b157-317f9b4c054b.png)

**Comment by JustinBack** [comment]
Thanks for reporting this! The underlying node is back to healthy status again!
