### ISSUE TITLE
Getting a 500 for every GET request

### ISSUE THREAD

**Issue by EvilWatermelon** [tosdr/API#19]
I can call every API endpoint and get a 500.

`$ curl -i -X GET https://api.tosdr.org/service/v1/?service=wikipedia.org`

```
HTTP/2 500 
apisix-cache-status: MISS
content-type: application/json
date: Fri, 26 Jul 2024 06:01:11 GMT
server: traefik
vary: Accept-Encoding
x-apisix-upstream-status: 500
x-cluster: JIT_VE
x-ratelimit-limit: 5
x-ratelimit-remaining: 4
x-ratelimit-reset: 10
x-request-id: c6c74f77-79d9-48a4-a7b2-d39589ee674f

{"error":1,"message":"Internal Server Error","parameters":{"Trace":"ParserProxy"}}
```

**Comment by radkoff** [comment]
Sorry for the delay. As per the [documentation](https://developers.tosdr.org/dev/get-service-v2) that endpoint takes an integer service ID as a query param, for example `curl https://api.tosdr.org/service/v2/?id=356`. You can omit `id` to list all Services, or use the [search API](https://developers.tosdr.org/dev/get-search-v4) to find what you're looking for
